import { GraphQLScalarType, GraphQLError, Kind } from "graphql";
import { fromGlobalId } from "graphql-relay";

export const GlobalIdInput = new GraphQLScalarType({
  name: "GlobalIdInput",
  description:
    "The GlobalIdInput scalar type represents the global id generated by relay.",
  serialize(globalId: string): string {
    return globalId;
  },
  parseValue(value: string): number {
    try {
      const parsed = fromGlobalId(value).id;

      return parseInt(parsed, 10);
    } catch (error) {
      throw new GraphQLError(`No valid ID extracted from ${value}`);
    }
  },
  parseLiteral(ast): number {
    try {
      if (ast.kind === Kind.STRING) {
        const parsed = fromGlobalId(ast.value).id;

        return parseInt(parsed, 10);
      }

      return null;
    } catch (error) {
      if (ast.kind === Kind.STRING) {
        throw new GraphQLError(`No valid ID extracted from ${ast.value}`);
      }
      throw new GraphQLError("No valid ID extracted.");
    }
  }
});
